### ISSUE TITLE
Add support for KDL1

### ISSUE THREAD

**Issue by lf94** [lf94/kdl2viewer#3]
https://github.com/huderlem/kirbydreamland has reversed KDL1's format. It looks very similar.

@huderlem maybe you would like to add it? :)

**Comment by huderlem** [comment]
Sure, I could take a look at extending this tool next week-ish.  I'm curious how you discovered my disassembly?

**Comment by lf94** [comment]
The all seeing #gbdev eye. :)

**Comment by lf94** [comment]
Resolved by Mr. @huderlem ! Great work.
